### ISSUE TITLE
New Terraform plugin (and Golang integration)

### ISSUE THREAD

**Issue by vancluever** [phpipam/phpipam-api-clients#10]
Hey @phpipam! And anyone else reading :)

Just wanted to pass along 2 new integrations that I created to help us at @paybyphone and how we work with PHPIPAM. I don't know if these are really good to submodule TBH, one of them definitely isn't and the other one is better fetched using any go package management tool or a simple `go get -d`.

Anyway, here we go:

## Terraform Plugin

I created a [Terraform][1] plugin that you can find at https://github.com/paybyphone/terraform-provider-phpipam. There are both data sources and resources for sections, vlans, subnets, and addresses. The subnet and address data sources also have options for searching on description and hostname (and the subnet has a regex match feature as well). Detailed docs on installation and usage can be found there, in addition to downloads for both TF v0.9.x and v0.8.x for those that haven't updated yet.

[1]: https://www.terraform.io/

## Go SDK

To support the TF development efforts, and also to write a migration tool for our old pre-1.0 version, I wrote https://github.com/paybyphone/phpipam-sdk-go as well. Not everything in the API is implemented, but it's dead easy to extend to the point where writing the tests takes longer than writing the new implementations. The README is still sparse, but the godoc has tons of info on how to work with the SDK.

## PHPIPAM 1.3 support?

I'll put this in phpipam/phpipam#1020 as well just for a quick update, but I have been developing against the PHPIPAM 1.2 release. Any info on when 1.3 will be out would be welcome and I'd be happy to update both the plugin and SDK to ensure that it works, if anything needed to be updated. I have tried as much as possible to follow the spec though, so if the docs on the website are up to date enough, hopefully there are no regressions.

-----

Anyway, just wanted to pass these along! If there's anywhere I can put this info without adding a submodule, let me know and I'll do the needful! Cheers!

**Comment by ameukam** [comment]
hi @vancluever. I wonder if there any chance to get a new release of https://github.com/paybyphone/terraform-provider-phpipam working with 1.3 ? I don't know if it's still maintained or in freeze ?

**Comment by vancluever** [comment]
Hey @ameukam I don't work for PBP anymore and am now quite busy at my new position at HashiCorp, so I haven't been maintaining this, and I'm not too sure how much in the way of work it would take to get it 100% functional... sorry!
