### ISSUE TITLE
multiple parameters using crypt APIs

### ISSUE THREAD

**Issue by ajwm** [phpipam/phpipam-api-clients#2]
I think line 550 in class.phpipam-api.php should read
       `   else        { $this->api_server_identifiers['id'.($cnt+1)] = $i; }`
instead of the current
       `   else       { $this->api_server_identifiers['id'.$i] = $i; }`

Otherwise additional ids get messed up, unless I'm totally misunderstanding the way the id and parameter arrays passed to API->execute() are to be used.

The above change gives me the expected result for e.g.
   `$API->execute("GET", "subnets", [20,"first_free"], array(), $token_file);`

Cheers.

**Comment by ajwm** [comment]
I forked the repo to ajwm/phpipam-api-clients and committed my fix there.   (I'm still figuring my way around GitHub, we use GitLab at work.)

**Comment by ajwm** [comment]
Created a pull request for my fix.

**Comment by phpipam** [comment]
MErged, thanks
